myvariable: local

spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
